name: "Infra Change Management"
# https://spacelift.io/blog/github-actions-terraform

on:
  workflow_call:
    inputs:
      tf-folder-path:
        required: false
        type: string
        default: "/infra"
      ref:
        required: false
        type: string
        default: "main"
      force-deploy:
        required: false
        type: boolean
        default: false
    outputs:
      tf-outputs:
        description: "The JSON output from the primary Terraform script, if applicable"
        value: ${{ jobs.infra.outputs.tf-outputs-general }}
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      TF_STATE_S3_BUCKET_ARN:
        required: true
      TF_STATE_LOCK_DYNAMODB_ARN:
        required: true

permissions:
  actions: write
  checks: write
  contents: read
  issues: write
  pull-requests: write
  id-token: write # Used for the GitHub OIDC Flow

jobs:
  infra:
    name: "Infra Change Management"
    runs-on: ubuntu-latest
    outputs:
      tf-outputs-general: ${{ steps.tf-flow-general.outputs.tf-output }}
    env: 
      TF_LOG: INFO
      full_tf_folder_path: ${{ github.workspace }}${{ inputs.tf-folder-path }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository that triggered the workflow
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
          sparse-checkout: |
            .github
            infra
      - name: Checkout the repository where this workflow lives
        if: ${{ github.repository != 'mechwire/tf-state-remote-backend' }}
        uses: actions/checkout@v4
        with: 
          repository: 'mechwire/tf-state-remote-backend'
          sparse-checkout: |
            .github/actions
          path: ./.temp
      - name: Move workflow-specific files to normal repo structure, for action
        if: ${{ github.repository != 'mechwire/tf-state-remote-backend' }}
        run: >
            mkdir -p ./.github/actions;
            mv ./.temp/.github/actions/* ./.github/actions/;
      - name: Define semi-dynamic environmental variables
        run: >
            echo "TFBACKEND_FILE_NAME=$(readlink -f ./gh.tfbackend)" >> $GITHUB_ENV;
            echo "TFVAR_FILE_NAME=$(readlink -f ./gh.tfvars)" >> $GITHUB_ENV;
      - name: Setup TF
        uses: ./.github/actions/tf-setup
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          aws-region:  ${{ secrets.AWS_REGION }}
          repo-specific-secrets: ${{ toJSON(secrets) }}
          tfbackend-file-name: ${{ env.TFBACKEND_FILE_NAME }}
          tfvar-file-name: ${{ env.TFVAR_FILE_NAME }}
          tfstate-s3-bucket-arn: ${{ secrets.TF_STATE_S3_BUCKET_ARN }}
          tfstate-lock-dynamodb-arn: ${{ secrets.TF_STATE_LOCK_DYNAMODB_ARN }}
      - name: TF Flow - Repo Setup
        if: ${{ hashFiles(format('{0}/setup/**.tf', env.full_tf_folder_path)) != '' }}
        id: tf-flow-repo-setup
        uses: ./.github/actions/tf-init-apply
        with:
          directory: ${{ env.full_tf_folder_path}}/setup
          tf-component-name: repo-setup
          aws-region:  ${{ secrets.AWS_REGION }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          # github.com/mechwire/github-oidc-role
          aws-role-to-assume: github_infra_role_provisioner
          tfbackend-file-name: ${{ env.TFBACKEND_FILE_NAME }}
          tfvar-file-name:  ${{ env.TFVAR_FILE_NAME }}
          force-deploy: ${{ inputs.force-deploy }}
        continue-on-error: true
      - name: TF Flow - General Functionality
        if: ${{ hashFiles(format('{0}/**.tf', env.full_tf_folder_path)) != '' && steps.tf-flow-repo-setup.outcome == 'success' }}
        id: tf-flow-general
        uses: ./.github/actions/tf-init-apply
        with:
          directory: ${{ env.full_tf_folder_path}}
          tf-component-name: general
          aws-region:  ${{ secrets.AWS_REGION }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-role-to-assume:  github_infra_${{ github.event.repository.name }}
          tfbackend-file-name: ${{ env.TFBACKEND_FILE_NAME }}
          tfvar-file-name:  ${{ env.TFVAR_FILE_NAME }}
          force-deploy: ${{ inputs.force-deploy }}
        continue-on-error: true
      - name: Update PR with TF Statuses
        uses: actions/github-script@v7
        if: github.ref != 'refs/heads/main' && github.event_name == 'push'
        env:
            setup_outcome: ${{ steps.tf-flow-repo-setup.outputs.summary }}
            general_outcome: ${{ steps.tf-flow-general.outputs.summary }}
            aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/actions/github-script/issues/273#issuecomment-1257245316
          script: |
              // Get pull requests that are open for current ref.
              const pullRequests = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open',
                  head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
              })

              if (pullRequests.data.length == 0) {
                return
              }

              // Set issue number for following calls from context (if on pull request event) or from above variable.
              const issueNumber = context.issue.number || pullRequests.data[0].number

              // Retrieve existing bot comments for the PR
              const {
                  data: comments
              } = await github.rest.issues.listComments({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
              })
              const botComment = comments.find(comment => {
                  return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan')
              })


              let output = `# Terraform Plan
              `

              for (let outcome of [process.env.setup_outcome, process.env.general_outcome]) {

                  let hasFailure = false
                  let parsedOutcome;

                  try {
                    parsedOutcome = JSON.parse(outcome)
                  } catch (e) {
                    console.log(e)
                    continue
                  }
                  

                  let name = parsedOutcome.name
                  delete parsedOutcome.name

                  let stdout = parsedOutcome.plan_stdout
                  stdout = stdout.replace(process.env.aws_account_id, "XXXXX")
                  delete parsedOutcome.plan_stdout

                  let stderr = parsedOutcome.plan_stderr
                  delete parsedOutcome.plan_stderr

                  let emojiOutcomes = new Map();
                  for (const [step, outcome] of Object.entries(parsedOutcome)) {
                      if (outcome == 'failure') {
                          hasFailure = true
                          emojiOutcomes.set(step, ':x:')
                      } else {
                          emojiOutcomes.set(step, ':white_check_mark:')
                      }
                  }

                  output += `

              ## ${name}

              |  Step      |   Outcome                        |
              |------------|----------------------------------|
              | \`init\`     | ${emojiOutcomes.get("init")}     |
              | \`fmt\`      | ${emojiOutcomes.get("fmt")}      |
              | \`validate\` | ${emojiOutcomes.get("validate")} |
              | \`plan\`     | ${emojiOutcomes.get("plan")}     |

              `

                  if (!hasFailure) {
                      output += `
              <details><summary>Show Plan</summary>
              
              \`\`\`terraform
              ${stdout.trimEnd()}
              \`\`\`

              </details>
              `
                  } else {
                      output += `Errors Found. Check Github Actions logs for detail.`
                  }
              }

              // If we have a comment, update it, otherwise create a new one
              if (botComment) {
                  github.rest.issues.updateComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      comment_id: botComment.id,
                      body: output
                  })
              } else {
                  github.rest.issues.createComment({
                      issue_number: issueNumber,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: output
                  })
              }
      - name: Reflect Failure Status if Needed
        if: ${{ steps.tf-flow-repo-setup.outcome == 'failure' ||  steps.tf-flow-general.outcome == 'failure'}}
        shell: bash
        run: exit 1
